//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// FindWithDrawCash
    /// </summary>
    public partial class FindWithDrawCash
    {
        /// <summary>
        /// 
        /// </summary>
        public int FwcId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> FuId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> FaId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> FwcAmount { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> FwcWithDrawDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FwcWithDrawStatus { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FwcWithDrawIntroduce { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Fwc { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> FwcAuditDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FwcOperator { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> FwcOperateDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> FwcStatus { get; set; }
    
        public virtual FindAccounts FindAccounts { get; set; }
        public virtual FindUsers FindUsers { get; set; }
    }
}
