//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// FindFlow
    /// </summary>
    public partial class FindFlow
    {
        /// <summary>
        /// 
        /// </summary>
        public int FfId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> FuId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FfNumber { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> FfDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FfType { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FfDetails { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> FfAmountPaid { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> FfAmountReceived { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FfBindNumber { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> FfAutidingDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FfExchangeStatus { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FfOperator { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> FfOperateDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> FfStatus { get; set; }
    
        public virtual FindUsers FindUsers { get; set; }
    }
}
