//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// FindBackList
    /// </summary>
    public partial class FindBackList
    {
        /// <summary>
        /// 
        /// </summary>
        public int FbId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> FuId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> FbBackId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> FbAddDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string DbOperator { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> DbOperateDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> DbStatus { get; set; }
    
        public virtual FindUsers FindUsers { get; set; }
    }
}
