//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// FindHonor
    /// </summary>
    public partial class FindHonor
    {
        /// <summary>
        /// 
        /// </summary>
        public int FhoId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> FuId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FhoName { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> FhoValue { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FhoUnit { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FhoDescribe { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FhoOperator { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> FhoOperateDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> FhoStatus { get; set; }
    
        public virtual FindUsers FindUsers { get; set; }
    }
}
