//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// FindProduct
    /// </summary>
    public partial class FindProduct
    {
        /// <summary>
        /// 
        /// </summary>
        public int FpId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FpName { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> FpPrice { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FpDescribe { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FpPicture { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> FpCostPrice { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> FpStock { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FpOperator { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> FpOperateDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> FpStatus { get; set; }
    }
}
