//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// FindDictionary
    /// </summary>
    public partial class FindDictionary
    {
        /// <summary>
        /// 
        /// </summary>
        public int FdId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FdType { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FdName { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FdValue { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FdRemark { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> FdParentId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FdDictionaryStatus { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FdOperator { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> FdOperateDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> FdStatus { get; set; }
    }
}
