//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// FindDevice
    /// </summary>
    public partial class FindDevice
    {
        /// <summary>
        /// 
        /// </summary>
        public int FdeId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> FuId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FdeName { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FdeFunction { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FdeDescriabe { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FdeOperator { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> FdeOperateDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> FdeStatus { get; set; }
    
        public virtual FindUsers FindUsers { get; set; }
    }
}
