//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// FindFriends
    /// </summary>
    public partial class FindFriends
    {
        /// <summary>
        /// 
        /// </summary>
        public int FfrId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> FuId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> FfgId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> FfrFriendsId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> FfrInterest { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FfrRemark { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> FfrAddDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FfrFriendStatus { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FfrOperator { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> FfrOperateDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> FfrStatus { get; set; }
    
        public virtual FindFriendGroup FindFriendGroup { get; set; }
        public virtual FindUsers FindUsers { get; set; }
    }
}
