//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// FindAdversitement
    /// </summary>
    public partial class FindAdversitement
    {
        /// <summary>
        /// 
        /// </summary>
        public int FadId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> FalId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FadName { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FadTitle { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FadContnet { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> FadPubDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> FadOutDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FadCompany { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FadFeeScale { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> FadPrice { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FadAdStatus { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FadOperator { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> FadOperateDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> FadStatus { get; set; }
    
        public virtual FindAlimama FindAlimama { get; set; }
    }
}
