//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// FindGame
    /// </summary>
    public partial class FindGame
    {
        public FindGame()
        {
            this.FindGameRoom = new HashSet<FindGameRoom>();
        }
    
        /// <summary>
        /// 
        /// </summary>
        public int FgId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FgName { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FgType { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FgDescribe { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> FgPersonCount { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FgPlayIntrodece { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FgOperator { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> FgOperateDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> FgStatus { get; set; }
    
        public virtual ICollection<FindGameRoom> FindGameRoom { get; set; }
    }
}
