//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// FindTrends
    /// </summary>
    public partial class FindTrends
    {
        public FindTrends()
        {
            this.FindTrendComments = new HashSet<FindTrendComments>();
        }
    
        /// <summary>
        /// 
        /// </summary>
        public int FtrId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> FuId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FtrTitle { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FtrContent { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FtrAppendix { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> FtrPublishDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FtrFrom { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> FtrReadCount { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> FtrLinks { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FtrOperator { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> FtrOperateDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> FtrStatus { get; set; }
    
        public virtual ICollection<FindTrendComments> FindTrendComments { get; set; }
        public virtual FindUsers FindUsers { get; set; }
    }
}
