//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// FindCircle
    /// </summary>
    public partial class FindCircle
    {
        /// <summary>
        /// 
        /// </summary>
        public int FcId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> FuId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FcName { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FcIntroduce { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FcType { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> FcLevel { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FcIcon { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> FcCreateDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FcOperator { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> FcOperateDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> FcStatus { get; set; }
    
        public virtual FindUsers FindUsers { get; set; }
    }
}
