//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// FindVerify
    /// </summary>
    public partial class FindVerify
    {
        /// <summary>
        /// 
        /// </summary>
        public int FveId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> FuId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FveType { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FveQuestion { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FveAnswer { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FveFor { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FveVerifyStatus { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FveOperator { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> FveOperateDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> FveStatus { get; set; }
    
        public virtual FindUsers FindUsers { get; set; }
    }
}
