//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// FindAccounts
    /// </summary>
    public partial class FindAccounts
    {
        public FindAccounts()
        {
            this.FindWithDrawCash = new HashSet<FindWithDrawCash>();
        }
    
        /// <summary>
        /// 
        /// </summary>
        public int FaId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> FuId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FaName { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> FaBalance { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FaNumber { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FaOperator { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> FaOperateDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> FaStatus { get; set; }
    
        public virtual FindUsers FindUsers { get; set; }
        public virtual ICollection<FindWithDrawCash> FindWithDrawCash { get; set; }
    }
}
