//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// FindTrendComments
    /// </summary>
    public partial class FindTrendComments
    {
        /// <summary>
        /// 
        /// </summary>
        public int FtcId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> FtrId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> FuId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FtcAppendix { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> FtcPublishDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FtcContent { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> FtcReadCounts { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> FtcLisks { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FtcOperator { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> FtcOperateDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> FtcStatus { get; set; }
    
        public virtual FindTrends FindTrends { get; set; }
        public virtual FindUsers FindUsers { get; set; }
    }
}
