//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// FindGameRoom
    /// </summary>
    public partial class FindGameRoom
    {
        /// <summary>
        /// 
        /// </summary>
        public int FgrId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> FuId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> FgId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FgrName { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FgrNumber { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> FgrPersonCount { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FgrGameStatus { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FgrOperator { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> FgrOperateDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> FgrStatus { get; set; }
    
        public virtual FindGame FindGame { get; set; }
        public virtual FindUsers FindUsers { get; set; }
    }
}
