//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// FindApply
    /// </summary>
    public partial class FindApply
    {
        /// <summary>
        /// 
        /// </summary>
        public int FapId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> FuId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FapType { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FapFor { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> FapApplyDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FapApplyDescribe { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FapApplyStatus { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FapOperator { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> FapOperateDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> FapStatus { get; set; }
    
        public virtual FindUsers FindUsers { get; set; }
    }
}
