//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// FindInterest
    /// </summary>
    public partial class FindInterest
    {
        /// <summary>
        /// 
        /// </summary>
        public int FiId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FiName { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FiIntroduce { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FiOperator { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> FiOperateDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> FiStatus { get; set; }
    }
}
