//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// FindMessage
    /// </summary>
    public partial class FindMessage
    {
        /// <summary>
        /// 
        /// </summary>
        public int FmId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> FuId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FmTitle { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FmContent { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FmReceives { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FmType { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> FmSendDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FmOperator { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> FmOperateDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> FmStatus { get; set; }
    
        public virtual FindUsers FindUsers { get; set; }
    }
}
