//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// FindPower
    /// </summary>
    public partial class FindPower
    {
        /// <summary>
        /// 
        /// </summary>
        public int FpoId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> FuId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FpoName { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FpoDescribe { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> FpoValue { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FpoOperator { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> FpoOperateDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> FpoStatus { get; set; }
    
        public virtual FindUsers FindUsers { get; set; }
    }
}
