//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BlueVacationEntities : DbContext
    {
        public BlueVacationEntities()
            : base("name=BlueVacationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<FindAccounts> FindAccounts { get; set; }
        public DbSet<FindAdversitement> FindAdversitement { get; set; }
        public DbSet<FindAlimama> FindAlimama { get; set; }
        public DbSet<FindApply> FindApply { get; set; }
        public DbSet<FindBackList> FindBackList { get; set; }
        public DbSet<FindCircle> FindCircle { get; set; }
        public DbSet<FindDevice> FindDevice { get; set; }
        public DbSet<FindDictionary> FindDictionary { get; set; }
        public DbSet<FindDocument> FindDocument { get; set; }
        public DbSet<FindFlow> FindFlow { get; set; }
        public DbSet<FindFriendGroup> FindFriendGroup { get; set; }
        public DbSet<FindFriends> FindFriends { get; set; }
        public DbSet<FindGame> FindGame { get; set; }
        public DbSet<FindGameRoom> FindGameRoom { get; set; }
        public DbSet<FindHonor> FindHonor { get; set; }
        public DbSet<FindInterest> FindInterest { get; set; }
        public DbSet<FindMessage> FindMessage { get; set; }
        public DbSet<FindMoney> FindMoney { get; set; }
        public DbSet<FindPower> FindPower { get; set; }
        public DbSet<FindProduct> FindProduct { get; set; }
        public DbSet<FindPublicMessage> FindPublicMessage { get; set; }
        public DbSet<FindRecharge> FindRecharge { get; set; }
        public DbSet<FindTrendComments> FindTrendComments { get; set; }
        public DbSet<FindTrends> FindTrends { get; set; }
        public DbSet<FindUsers> FindUsers { get; set; }
        public DbSet<FindVerify> FindVerify { get; set; }
        public DbSet<FindWithDrawCash> FindWithDrawCash { get; set; }
    }
}
