//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.MobileMessage_56 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MobileMessage_56.WebServiceInterfaceSoap")]
    public interface WebServiceInterfaceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 userName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UserLogin", ReplyAction="*")]
        Web.MobileMessage_56.UserLoginResponse UserLogin(Web.MobileMessage_56.UserLoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UserLogin", ReplyAction="*")]
        System.Threading.Tasks.Task<Web.MobileMessage_56.UserLoginResponse> UserLoginAsync(Web.MobileMessage_56.UserLoginRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 username 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditUserPwd", ReplyAction="*")]
        Web.MobileMessage_56.EditUserPwdResponse EditUserPwd(Web.MobileMessage_56.EditUserPwdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditUserPwd", ReplyAction="*")]
        System.Threading.Tasks.Task<Web.MobileMessage_56.EditUserPwdResponse> EditUserPwdAsync(Web.MobileMessage_56.EditUserPwdRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 username 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnUserFullMoney", ReplyAction="*")]
        Web.MobileMessage_56.ReturnUserFullMoneyResponse ReturnUserFullMoney(Web.MobileMessage_56.ReturnUserFullMoneyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnUserFullMoney", ReplyAction="*")]
        System.Threading.Tasks.Task<Web.MobileMessage_56.ReturnUserFullMoneyResponse> ReturnUserFullMoneyAsync(Web.MobileMessage_56.ReturnUserFullMoneyRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 handtels 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendNote", ReplyAction="*")]
        Web.MobileMessage_56.SendNoteResponse SendNote(Web.MobileMessage_56.SendNoteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendNote", ReplyAction="*")]
        System.Threading.Tasks.Task<Web.MobileMessage_56.SendNoteResponse> SendNoteAsync(Web.MobileMessage_56.SendNoteRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 handtels 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendNoteState", ReplyAction="*")]
        Web.MobileMessage_56.SendNoteStateResponse SendNoteState(Web.MobileMessage_56.SendNoteStateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendNoteState", ReplyAction="*")]
        System.Threading.Tasks.Task<Web.MobileMessage_56.SendNoteStateResponse> SendNoteStateAsync(Web.MobileMessage_56.SendNoteStateRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 aid 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FullMoney", ReplyAction="*")]
        Web.MobileMessage_56.FullMoneyResponse FullMoney(Web.MobileMessage_56.FullMoneyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FullMoney", ReplyAction="*")]
        System.Threading.Tasks.Task<Web.MobileMessage_56.FullMoneyResponse> FullMoneyAsync(Web.MobileMessage_56.FullMoneyRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 _cid 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NoteBack", ReplyAction="*")]
        Web.MobileMessage_56.NoteBackResponse NoteBack(Web.MobileMessage_56.NoteBackRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NoteBack", ReplyAction="*")]
        System.Threading.Tasks.Task<Web.MobileMessage_56.NoteBackResponse> NoteBackAsync(Web.MobileMessage_56.NoteBackRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 aid 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddNewUser", ReplyAction="*")]
        Web.MobileMessage_56.AddNewUserResponse AddNewUser(Web.MobileMessage_56.AddNewUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddNewUser", ReplyAction="*")]
        System.Threading.Tasks.Task<Web.MobileMessage_56.AddNewUserResponse> AddNewUserAsync(Web.MobileMessage_56.AddNewUserRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UserLoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UserLogin", Namespace="http://tempuri.org/", Order=0)]
        public Web.MobileMessage_56.UserLoginRequestBody Body;
        
        public UserLoginRequest() {
        }
        
        public UserLoginRequest(Web.MobileMessage_56.UserLoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UserLoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string cid;
        
        public UserLoginRequestBody() {
        }
        
        public UserLoginRequestBody(string userName, string password, string cid) {
            this.userName = userName;
            this.password = password;
            this.cid = cid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UserLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UserLoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public Web.MobileMessage_56.UserLoginResponseBody Body;
        
        public UserLoginResponse() {
        }
        
        public UserLoginResponse(Web.MobileMessage_56.UserLoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UserLoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UserLoginResult;
        
        public UserLoginResponseBody() {
        }
        
        public UserLoginResponseBody(int UserLoginResult) {
            this.UserLoginResult = UserLoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditUserPwdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditUserPwd", Namespace="http://tempuri.org/", Order=0)]
        public Web.MobileMessage_56.EditUserPwdRequestBody Body;
        
        public EditUserPwdRequest() {
        }
        
        public EditUserPwdRequest(Web.MobileMessage_56.EditUserPwdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditUserPwdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userpwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string newpwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string cid;
        
        public EditUserPwdRequestBody() {
        }
        
        public EditUserPwdRequestBody(string username, string userpwd, string newpwd, string cid) {
            this.username = username;
            this.userpwd = userpwd;
            this.newpwd = newpwd;
            this.cid = cid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditUserPwdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditUserPwdResponse", Namespace="http://tempuri.org/", Order=0)]
        public Web.MobileMessage_56.EditUserPwdResponseBody Body;
        
        public EditUserPwdResponse() {
        }
        
        public EditUserPwdResponse(Web.MobileMessage_56.EditUserPwdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditUserPwdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int EditUserPwdResult;
        
        public EditUserPwdResponseBody() {
        }
        
        public EditUserPwdResponseBody(int EditUserPwdResult) {
            this.EditUserPwdResult = EditUserPwdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReturnUserFullMoneyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReturnUserFullMoney", Namespace="http://tempuri.org/", Order=0)]
        public Web.MobileMessage_56.ReturnUserFullMoneyRequestBody Body;
        
        public ReturnUserFullMoneyRequest() {
        }
        
        public ReturnUserFullMoneyRequest(Web.MobileMessage_56.ReturnUserFullMoneyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReturnUserFullMoneyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string cid;
        
        public ReturnUserFullMoneyRequestBody() {
        }
        
        public ReturnUserFullMoneyRequestBody(string username, string password, string cid) {
            this.username = username;
            this.password = password;
            this.cid = cid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReturnUserFullMoneyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReturnUserFullMoneyResponse", Namespace="http://tempuri.org/", Order=0)]
        public Web.MobileMessage_56.ReturnUserFullMoneyResponseBody Body;
        
        public ReturnUserFullMoneyResponse() {
        }
        
        public ReturnUserFullMoneyResponse(Web.MobileMessage_56.ReturnUserFullMoneyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReturnUserFullMoneyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ReturnUserFullMoneyResult;
        
        public ReturnUserFullMoneyResponseBody() {
        }
        
        public ReturnUserFullMoneyResponseBody(int ReturnUserFullMoneyResult) {
            this.ReturnUserFullMoneyResult = ReturnUserFullMoneyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendNoteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendNote", Namespace="http://tempuri.org/", Order=0)]
        public Web.MobileMessage_56.SendNoteRequestBody Body;
        
        public SendNoteRequest() {
        }
        
        public SendNoteRequest(Web.MobileMessage_56.SendNoteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendNoteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string handtels;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string _content;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string cid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string _sendtime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string _smsnumber;
        
        public SendNoteRequestBody() {
        }
        
        public SendNoteRequestBody(string handtels, string _content, string userName, string password, string cid, string _sendtime, string _smsnumber) {
            this.handtels = handtels;
            this._content = _content;
            this.userName = userName;
            this.password = password;
            this.cid = cid;
            this._sendtime = _sendtime;
            this._smsnumber = _smsnumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendNoteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendNoteResponse", Namespace="http://tempuri.org/", Order=0)]
        public Web.MobileMessage_56.SendNoteResponseBody Body;
        
        public SendNoteResponse() {
        }
        
        public SendNoteResponse(Web.MobileMessage_56.SendNoteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendNoteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SendNoteResult;
        
        public SendNoteResponseBody() {
        }
        
        public SendNoteResponseBody(int SendNoteResult) {
            this.SendNoteResult = SendNoteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendNoteStateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendNoteState", Namespace="http://tempuri.org/", Order=0)]
        public Web.MobileMessage_56.SendNoteStateRequestBody Body;
        
        public SendNoteStateRequest() {
        }
        
        public SendNoteStateRequest(Web.MobileMessage_56.SendNoteStateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendNoteStateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string handtels;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string _content;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string cid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string _sendtime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string _smsnumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string _stateid;
        
        public SendNoteStateRequestBody() {
        }
        
        public SendNoteStateRequestBody(string handtels, string _content, string userName, string password, string cid, string _sendtime, string _smsnumber, string _stateid) {
            this.handtels = handtels;
            this._content = _content;
            this.userName = userName;
            this.password = password;
            this.cid = cid;
            this._sendtime = _sendtime;
            this._smsnumber = _smsnumber;
            this._stateid = _stateid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendNoteStateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendNoteStateResponse", Namespace="http://tempuri.org/", Order=0)]
        public Web.MobileMessage_56.SendNoteStateResponseBody Body;
        
        public SendNoteStateResponse() {
        }
        
        public SendNoteStateResponse(Web.MobileMessage_56.SendNoteStateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SendNoteStateResponseBody {
        
        public SendNoteStateResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FullMoneyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FullMoney", Namespace="http://tempuri.org/", Order=0)]
        public Web.MobileMessage_56.FullMoneyRequestBody Body;
        
        public FullMoneyRequest() {
        }
        
        public FullMoneyRequest(Web.MobileMessage_56.FullMoneyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FullMoneyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string aid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string aname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string apwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string userid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string tomoney;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string action;
        
        public FullMoneyRequestBody() {
        }
        
        public FullMoneyRequestBody(string aid, string aname, string apwd, string userid, string username, string tomoney, string action) {
            this.aid = aid;
            this.aname = aname;
            this.apwd = apwd;
            this.userid = userid;
            this.username = username;
            this.tomoney = tomoney;
            this.action = action;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FullMoneyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FullMoneyResponse", Namespace="http://tempuri.org/", Order=0)]
        public Web.MobileMessage_56.FullMoneyResponseBody Body;
        
        public FullMoneyResponse() {
        }
        
        public FullMoneyResponse(Web.MobileMessage_56.FullMoneyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FullMoneyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FullMoneyResult;
        
        public FullMoneyResponseBody() {
        }
        
        public FullMoneyResponseBody(string FullMoneyResult) {
            this.FullMoneyResult = FullMoneyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NoteBackRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NoteBack", Namespace="http://tempuri.org/", Order=0)]
        public Web.MobileMessage_56.NoteBackRequestBody Body;
        
        public NoteBackRequest() {
        }
        
        public NoteBackRequest(Web.MobileMessage_56.NoteBackRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class NoteBackRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string _cid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string _username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string _userpwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string zid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string action;
        
        public NoteBackRequestBody() {
        }
        
        public NoteBackRequestBody(string _cid, string _username, string _userpwd, string zid, string action) {
            this._cid = _cid;
            this._username = _username;
            this._userpwd = _userpwd;
            this.zid = zid;
            this.action = action;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NoteBackResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NoteBackResponse", Namespace="http://tempuri.org/", Order=0)]
        public Web.MobileMessage_56.NoteBackResponseBody Body;
        
        public NoteBackResponse() {
        }
        
        public NoteBackResponse(Web.MobileMessage_56.NoteBackResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class NoteBackResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string NoteBackResult;
        
        public NoteBackResponseBody() {
        }
        
        public NoteBackResponseBody(string NoteBackResult) {
            this.NoteBackResult = NoteBackResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddNewUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddNewUser", Namespace="http://tempuri.org/", Order=0)]
        public Web.MobileMessage_56.AddNewUserRequestBody Body;
        
        public AddNewUserRequest() {
        }
        
        public AddNewUserRequest(Web.MobileMessage_56.AddNewUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddNewUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string aid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string auserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string apwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string nusername;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string npwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string customername;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string customertel;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string customerqq;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string customeremaill;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Sright;
        
        public AddNewUserRequestBody() {
        }
        
        public AddNewUserRequestBody(string aid, string auserName, string apwd, string nusername, string npwd, string customername, string customertel, string customerqq, string customeremaill, string Sright) {
            this.aid = aid;
            this.auserName = auserName;
            this.apwd = apwd;
            this.nusername = nusername;
            this.npwd = npwd;
            this.customername = customername;
            this.customertel = customertel;
            this.customerqq = customerqq;
            this.customeremaill = customeremaill;
            this.Sright = Sright;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddNewUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddNewUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public Web.MobileMessage_56.AddNewUserResponseBody Body;
        
        public AddNewUserResponse() {
        }
        
        public AddNewUserResponse(Web.MobileMessage_56.AddNewUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddNewUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddNewUserResult;
        
        public AddNewUserResponseBody() {
        }
        
        public AddNewUserResponseBody(string AddNewUserResult) {
            this.AddNewUserResult = AddNewUserResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceInterfaceSoapChannel : Web.MobileMessage_56.WebServiceInterfaceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceInterfaceSoapClient : System.ServiceModel.ClientBase<Web.MobileMessage_56.WebServiceInterfaceSoap>, Web.MobileMessage_56.WebServiceInterfaceSoap {
        
        public WebServiceInterfaceSoapClient() {
        }
        
        public WebServiceInterfaceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceInterfaceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceInterfaceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceInterfaceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web.MobileMessage_56.UserLoginResponse Web.MobileMessage_56.WebServiceInterfaceSoap.UserLogin(Web.MobileMessage_56.UserLoginRequest request) {
            return base.Channel.UserLogin(request);
        }
        
        public int UserLogin(string userName, string password, string cid) {
            Web.MobileMessage_56.UserLoginRequest inValue = new Web.MobileMessage_56.UserLoginRequest();
            inValue.Body = new Web.MobileMessage_56.UserLoginRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.cid = cid;
            Web.MobileMessage_56.UserLoginResponse retVal = ((Web.MobileMessage_56.WebServiceInterfaceSoap)(this)).UserLogin(inValue);
            return retVal.Body.UserLoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Web.MobileMessage_56.UserLoginResponse> Web.MobileMessage_56.WebServiceInterfaceSoap.UserLoginAsync(Web.MobileMessage_56.UserLoginRequest request) {
            return base.Channel.UserLoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<Web.MobileMessage_56.UserLoginResponse> UserLoginAsync(string userName, string password, string cid) {
            Web.MobileMessage_56.UserLoginRequest inValue = new Web.MobileMessage_56.UserLoginRequest();
            inValue.Body = new Web.MobileMessage_56.UserLoginRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.cid = cid;
            return ((Web.MobileMessage_56.WebServiceInterfaceSoap)(this)).UserLoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web.MobileMessage_56.EditUserPwdResponse Web.MobileMessage_56.WebServiceInterfaceSoap.EditUserPwd(Web.MobileMessage_56.EditUserPwdRequest request) {
            return base.Channel.EditUserPwd(request);
        }
        
        public int EditUserPwd(string username, string userpwd, string newpwd, string cid) {
            Web.MobileMessage_56.EditUserPwdRequest inValue = new Web.MobileMessage_56.EditUserPwdRequest();
            inValue.Body = new Web.MobileMessage_56.EditUserPwdRequestBody();
            inValue.Body.username = username;
            inValue.Body.userpwd = userpwd;
            inValue.Body.newpwd = newpwd;
            inValue.Body.cid = cid;
            Web.MobileMessage_56.EditUserPwdResponse retVal = ((Web.MobileMessage_56.WebServiceInterfaceSoap)(this)).EditUserPwd(inValue);
            return retVal.Body.EditUserPwdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Web.MobileMessage_56.EditUserPwdResponse> Web.MobileMessage_56.WebServiceInterfaceSoap.EditUserPwdAsync(Web.MobileMessage_56.EditUserPwdRequest request) {
            return base.Channel.EditUserPwdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Web.MobileMessage_56.EditUserPwdResponse> EditUserPwdAsync(string username, string userpwd, string newpwd, string cid) {
            Web.MobileMessage_56.EditUserPwdRequest inValue = new Web.MobileMessage_56.EditUserPwdRequest();
            inValue.Body = new Web.MobileMessage_56.EditUserPwdRequestBody();
            inValue.Body.username = username;
            inValue.Body.userpwd = userpwd;
            inValue.Body.newpwd = newpwd;
            inValue.Body.cid = cid;
            return ((Web.MobileMessage_56.WebServiceInterfaceSoap)(this)).EditUserPwdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web.MobileMessage_56.ReturnUserFullMoneyResponse Web.MobileMessage_56.WebServiceInterfaceSoap.ReturnUserFullMoney(Web.MobileMessage_56.ReturnUserFullMoneyRequest request) {
            return base.Channel.ReturnUserFullMoney(request);
        }
        
        public int ReturnUserFullMoney(string username, string password, string cid) {
            Web.MobileMessage_56.ReturnUserFullMoneyRequest inValue = new Web.MobileMessage_56.ReturnUserFullMoneyRequest();
            inValue.Body = new Web.MobileMessage_56.ReturnUserFullMoneyRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.cid = cid;
            Web.MobileMessage_56.ReturnUserFullMoneyResponse retVal = ((Web.MobileMessage_56.WebServiceInterfaceSoap)(this)).ReturnUserFullMoney(inValue);
            return retVal.Body.ReturnUserFullMoneyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Web.MobileMessage_56.ReturnUserFullMoneyResponse> Web.MobileMessage_56.WebServiceInterfaceSoap.ReturnUserFullMoneyAsync(Web.MobileMessage_56.ReturnUserFullMoneyRequest request) {
            return base.Channel.ReturnUserFullMoneyAsync(request);
        }
        
        public System.Threading.Tasks.Task<Web.MobileMessage_56.ReturnUserFullMoneyResponse> ReturnUserFullMoneyAsync(string username, string password, string cid) {
            Web.MobileMessage_56.ReturnUserFullMoneyRequest inValue = new Web.MobileMessage_56.ReturnUserFullMoneyRequest();
            inValue.Body = new Web.MobileMessage_56.ReturnUserFullMoneyRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.cid = cid;
            return ((Web.MobileMessage_56.WebServiceInterfaceSoap)(this)).ReturnUserFullMoneyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web.MobileMessage_56.SendNoteResponse Web.MobileMessage_56.WebServiceInterfaceSoap.SendNote(Web.MobileMessage_56.SendNoteRequest request) {
            return base.Channel.SendNote(request);
        }
        
        public int SendNote(string handtels, string _content, string userName, string password, string cid, string _sendtime, string _smsnumber) {
            Web.MobileMessage_56.SendNoteRequest inValue = new Web.MobileMessage_56.SendNoteRequest();
            inValue.Body = new Web.MobileMessage_56.SendNoteRequestBody();
            inValue.Body.handtels = handtels;
            inValue.Body._content = _content;
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.cid = cid;
            inValue.Body._sendtime = _sendtime;
            inValue.Body._smsnumber = _smsnumber;
            Web.MobileMessage_56.SendNoteResponse retVal = ((Web.MobileMessage_56.WebServiceInterfaceSoap)(this)).SendNote(inValue);
            return retVal.Body.SendNoteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Web.MobileMessage_56.SendNoteResponse> Web.MobileMessage_56.WebServiceInterfaceSoap.SendNoteAsync(Web.MobileMessage_56.SendNoteRequest request) {
            return base.Channel.SendNoteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Web.MobileMessage_56.SendNoteResponse> SendNoteAsync(string handtels, string _content, string userName, string password, string cid, string _sendtime, string _smsnumber) {
            Web.MobileMessage_56.SendNoteRequest inValue = new Web.MobileMessage_56.SendNoteRequest();
            inValue.Body = new Web.MobileMessage_56.SendNoteRequestBody();
            inValue.Body.handtels = handtels;
            inValue.Body._content = _content;
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.cid = cid;
            inValue.Body._sendtime = _sendtime;
            inValue.Body._smsnumber = _smsnumber;
            return ((Web.MobileMessage_56.WebServiceInterfaceSoap)(this)).SendNoteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web.MobileMessage_56.SendNoteStateResponse Web.MobileMessage_56.WebServiceInterfaceSoap.SendNoteState(Web.MobileMessage_56.SendNoteStateRequest request) {
            return base.Channel.SendNoteState(request);
        }
        
        public void SendNoteState(string handtels, string _content, string userName, string password, string cid, string _sendtime, string _smsnumber, string _stateid) {
            Web.MobileMessage_56.SendNoteStateRequest inValue = new Web.MobileMessage_56.SendNoteStateRequest();
            inValue.Body = new Web.MobileMessage_56.SendNoteStateRequestBody();
            inValue.Body.handtels = handtels;
            inValue.Body._content = _content;
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.cid = cid;
            inValue.Body._sendtime = _sendtime;
            inValue.Body._smsnumber = _smsnumber;
            inValue.Body._stateid = _stateid;
            Web.MobileMessage_56.SendNoteStateResponse retVal = ((Web.MobileMessage_56.WebServiceInterfaceSoap)(this)).SendNoteState(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Web.MobileMessage_56.SendNoteStateResponse> Web.MobileMessage_56.WebServiceInterfaceSoap.SendNoteStateAsync(Web.MobileMessage_56.SendNoteStateRequest request) {
            return base.Channel.SendNoteStateAsync(request);
        }
        
        public System.Threading.Tasks.Task<Web.MobileMessage_56.SendNoteStateResponse> SendNoteStateAsync(string handtels, string _content, string userName, string password, string cid, string _sendtime, string _smsnumber, string _stateid) {
            Web.MobileMessage_56.SendNoteStateRequest inValue = new Web.MobileMessage_56.SendNoteStateRequest();
            inValue.Body = new Web.MobileMessage_56.SendNoteStateRequestBody();
            inValue.Body.handtels = handtels;
            inValue.Body._content = _content;
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.cid = cid;
            inValue.Body._sendtime = _sendtime;
            inValue.Body._smsnumber = _smsnumber;
            inValue.Body._stateid = _stateid;
            return ((Web.MobileMessage_56.WebServiceInterfaceSoap)(this)).SendNoteStateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web.MobileMessage_56.FullMoneyResponse Web.MobileMessage_56.WebServiceInterfaceSoap.FullMoney(Web.MobileMessage_56.FullMoneyRequest request) {
            return base.Channel.FullMoney(request);
        }
        
        public string FullMoney(string aid, string aname, string apwd, string userid, string username, string tomoney, string action) {
            Web.MobileMessage_56.FullMoneyRequest inValue = new Web.MobileMessage_56.FullMoneyRequest();
            inValue.Body = new Web.MobileMessage_56.FullMoneyRequestBody();
            inValue.Body.aid = aid;
            inValue.Body.aname = aname;
            inValue.Body.apwd = apwd;
            inValue.Body.userid = userid;
            inValue.Body.username = username;
            inValue.Body.tomoney = tomoney;
            inValue.Body.action = action;
            Web.MobileMessage_56.FullMoneyResponse retVal = ((Web.MobileMessage_56.WebServiceInterfaceSoap)(this)).FullMoney(inValue);
            return retVal.Body.FullMoneyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Web.MobileMessage_56.FullMoneyResponse> Web.MobileMessage_56.WebServiceInterfaceSoap.FullMoneyAsync(Web.MobileMessage_56.FullMoneyRequest request) {
            return base.Channel.FullMoneyAsync(request);
        }
        
        public System.Threading.Tasks.Task<Web.MobileMessage_56.FullMoneyResponse> FullMoneyAsync(string aid, string aname, string apwd, string userid, string username, string tomoney, string action) {
            Web.MobileMessage_56.FullMoneyRequest inValue = new Web.MobileMessage_56.FullMoneyRequest();
            inValue.Body = new Web.MobileMessage_56.FullMoneyRequestBody();
            inValue.Body.aid = aid;
            inValue.Body.aname = aname;
            inValue.Body.apwd = apwd;
            inValue.Body.userid = userid;
            inValue.Body.username = username;
            inValue.Body.tomoney = tomoney;
            inValue.Body.action = action;
            return ((Web.MobileMessage_56.WebServiceInterfaceSoap)(this)).FullMoneyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web.MobileMessage_56.NoteBackResponse Web.MobileMessage_56.WebServiceInterfaceSoap.NoteBack(Web.MobileMessage_56.NoteBackRequest request) {
            return base.Channel.NoteBack(request);
        }
        
        public string NoteBack(string _cid, string _username, string _userpwd, string zid, string action) {
            Web.MobileMessage_56.NoteBackRequest inValue = new Web.MobileMessage_56.NoteBackRequest();
            inValue.Body = new Web.MobileMessage_56.NoteBackRequestBody();
            inValue.Body._cid = _cid;
            inValue.Body._username = _username;
            inValue.Body._userpwd = _userpwd;
            inValue.Body.zid = zid;
            inValue.Body.action = action;
            Web.MobileMessage_56.NoteBackResponse retVal = ((Web.MobileMessage_56.WebServiceInterfaceSoap)(this)).NoteBack(inValue);
            return retVal.Body.NoteBackResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Web.MobileMessage_56.NoteBackResponse> Web.MobileMessage_56.WebServiceInterfaceSoap.NoteBackAsync(Web.MobileMessage_56.NoteBackRequest request) {
            return base.Channel.NoteBackAsync(request);
        }
        
        public System.Threading.Tasks.Task<Web.MobileMessage_56.NoteBackResponse> NoteBackAsync(string _cid, string _username, string _userpwd, string zid, string action) {
            Web.MobileMessage_56.NoteBackRequest inValue = new Web.MobileMessage_56.NoteBackRequest();
            inValue.Body = new Web.MobileMessage_56.NoteBackRequestBody();
            inValue.Body._cid = _cid;
            inValue.Body._username = _username;
            inValue.Body._userpwd = _userpwd;
            inValue.Body.zid = zid;
            inValue.Body.action = action;
            return ((Web.MobileMessage_56.WebServiceInterfaceSoap)(this)).NoteBackAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web.MobileMessage_56.AddNewUserResponse Web.MobileMessage_56.WebServiceInterfaceSoap.AddNewUser(Web.MobileMessage_56.AddNewUserRequest request) {
            return base.Channel.AddNewUser(request);
        }
        
        public string AddNewUser(string aid, string auserName, string apwd, string nusername, string npwd, string customername, string customertel, string customerqq, string customeremaill, string Sright) {
            Web.MobileMessage_56.AddNewUserRequest inValue = new Web.MobileMessage_56.AddNewUserRequest();
            inValue.Body = new Web.MobileMessage_56.AddNewUserRequestBody();
            inValue.Body.aid = aid;
            inValue.Body.auserName = auserName;
            inValue.Body.apwd = apwd;
            inValue.Body.nusername = nusername;
            inValue.Body.npwd = npwd;
            inValue.Body.customername = customername;
            inValue.Body.customertel = customertel;
            inValue.Body.customerqq = customerqq;
            inValue.Body.customeremaill = customeremaill;
            inValue.Body.Sright = Sright;
            Web.MobileMessage_56.AddNewUserResponse retVal = ((Web.MobileMessage_56.WebServiceInterfaceSoap)(this)).AddNewUser(inValue);
            return retVal.Body.AddNewUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Web.MobileMessage_56.AddNewUserResponse> Web.MobileMessage_56.WebServiceInterfaceSoap.AddNewUserAsync(Web.MobileMessage_56.AddNewUserRequest request) {
            return base.Channel.AddNewUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<Web.MobileMessage_56.AddNewUserResponse> AddNewUserAsync(string aid, string auserName, string apwd, string nusername, string npwd, string customername, string customertel, string customerqq, string customeremaill, string Sright) {
            Web.MobileMessage_56.AddNewUserRequest inValue = new Web.MobileMessage_56.AddNewUserRequest();
            inValue.Body = new Web.MobileMessage_56.AddNewUserRequestBody();
            inValue.Body.aid = aid;
            inValue.Body.auserName = auserName;
            inValue.Body.apwd = apwd;
            inValue.Body.nusername = nusername;
            inValue.Body.npwd = npwd;
            inValue.Body.customername = customername;
            inValue.Body.customertel = customertel;
            inValue.Body.customerqq = customerqq;
            inValue.Body.customeremaill = customeremaill;
            inValue.Body.Sright = Sright;
            return ((Web.MobileMessage_56.WebServiceInterfaceSoap)(this)).AddNewUserAsync(inValue);
        }
    }
}
